module.exports.descriptors = [
    'Jungle City',
    "Pete's",
    'Electric',
    'Soul City',
    'Groovy',
    'Allegra',
    'Tempo',
    "Cosmo's",
    'Freddy Land',
    'Village Music',
    'Rhythm',
    'Sound Hole',
    'Montage Sounds',
    'Ocean Waves',
    'Blue Sky',
    "Timmy's",
    "Dusty's",
    "Crescendo"
]

module.exports.places = [
    'Music Store',
    'Instrument Hamlet',
    'Sound',
    'Music Emporium',
    'Guitar Haven',
    'Synth Haven',
    'Audio World',
    'Audio Castle',
    'Music World',
    'Audio and Equipment',
    'Gear Emporium',
    'Music Repair Shop',
    'Pro',
    'Music Centre',
    'Music Boutique',
    'Media',
    'Vintage Music',
    'Drum Shop',
    'Music Connection',
    'Music LLC',
    'Guitar Works'
]

